// <auto-generated />
using System;
using BlackBeam.Services.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackBeam.Services.Identity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824170233_AddUsernameForStaff")]
    partial class AddUsernameForStaff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlackBeam.Services.Identity.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UsersDB", t =>
                        {
                            t.HasCheckConstraint("CK_User_Name_NotEmpty", "LENGTH(TRIM(Name)) > 0");

                            t.HasCheckConstraint("CK_User_PhoneNumber", "LENGTH(PhoneNumber) = 10 AND PhoneNumber LIKE '05%'");

                            t.HasCheckConstraint("CK_User_Role", "Role IN ('Admin', 'Cashier', 'Customer')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
